services:
  app:
    build: .
    volumes:
      - swiftq_data:/app/data
      - swiftq_static:/app/static
    environment:
      - TZ=America/Sao_Paulo
    restart: always

volumes:
  swiftq_data:
  swiftq_static:
